/* This example is borrowed from Apple's dispatch/base.h and dispatch/block.h */
#define DISPATCH_ENUM(name, type, ...) \
    enum { __VA_ARGS__ }; typedef type name##_t

DISPATCH_ENUM(test_single, int,
  TEST_SINGLE_ENTRY
);

DISPATCH_ENUM(test_single_with_value, int,
  TEST_SINGLE_ENTRY_WITH_VALUE = 0x1
);

#define DISPATCH_ENUM_AVAILABLE_STARTING(...)

DISPATCH_ENUM(test2, int,
  DISPATCH_TEST_ENUM_VALUE
      DISPATCH_ENUM_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0) = 0x1
);

DISPATCH_ENUM(dispatch_block_flags, unsigned long,
  DISPATCH_BLOCK_BARRIER
      DISPATCH_ENUM_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0) = 0x1,
  DISPATCH_BLOCK_DETACHED
      DISPATCH_ENUM_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0) = 0x2,
  DISPATCH_BLOCK_ASSIGN_CURRENT
      DISPATCH_ENUM_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0) = 0x4,
  DISPATCH_BLOCK_NO_QOS_CLASS
      DISPATCH_ENUM_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0) = 0x8,
  DISPATCH_BLOCK_INHERIT_QOS_CLASS
      DISPATCH_ENUM_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0) = 0x10,
  DISPATCH_BLOCK_ENFORCE_QOS_CLASS
      DISPATCH_ENUM_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0) = 0x20,
);

