name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dylan-lang/install-opendylan@v2

      - name: Build melange
        run: |
          ./dylan-compiler -build parsergen
          _build/bin/parsergen melange-core/c-parse.input melange-core/c-parse.dylan
          _build/bin/parsergen melange/int-parse.input melange/int-parse.dylan
          ./dylan-compiler -build melange

      - name: Run melange-tests
        run: tests/run.sh
